# Root
api:
  route: "/"
  controller: "HomeController"

entry:
  route: "entry"
  controller: "EntryController"

# POST REQUEST TO CREATE USER
register:
  route: "register"
  controller: "RegisterController"

# POST REQUEST TO LOGIN USER
login:
  route: "login"
  controller: "LoginController"

# GET REQUEST USER
user:
  route: "user"
  controller: "UserController"
